server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: service-gateway
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080
  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: http://localhost:8081
          predicates:
            - Path=/hotel-service/**
          filters:
            - StripPrefix=1
        - id: reservation-service
          uri: http://localhost:8082
          predicates:
            - Path=/reservation-service/**
          filters:
            - StripPrefix=1

